### PR TITLE
Add keyboard shortuct handlers to main window

### PR DESCRIPTION
**Pull request by marcosnils**
This allows to use shortcuts when visiting the page without having to
mage focus in the <App> component where there handlers are defined

### CODE REVIEW

**Comment by marcosnils** [comment]
Fixes #31 @ahmadabdolsaheb @QuincyLarson any chance to :eyes: this?

**Comment by ahmadabdolsaheb** [comment]
Thank you for submitting this solution.

Although this solution resolves #31 and is plausible,I encourage you find a similar solution that does not directly manipulate the DOM from a react component.

modules like react-hotkeys that is used in the main repo might be helpful.

**Comment by okbel** [comment]
@ahmadabdolsaheb Why is this issue being closed? Is there another thread where we should chat this?
Can't we handle the solution there?

Also, react-hotkeys provides a similar approach, but adding and removing events so it doesn't pollute the global scope. Can you point us to the file or approach you are referring? 
Thank you!

**Comment by marcosnils** [comment]
Hey @ahmadabdolsaheb. I don't really understand your suggestion. I've checked `react-hotkeys` and I can't find a way to attach hooks to the main window as it's needed here. Can you provide any guidance on how's the proper way to achieve this?

Furthermore, is it preferable add a new module which does the same thing to attach events to the main window (https://github.com/greena13/react-hotkeys/blob/f199c1ac93e13fd69e5751ef95043ebd3b21afa1/src/lib/KeyEventManager.js#L99) plus introducing possible errors than to just a single line that attaches the current defined controls?
I cannot find how doing that will be actually beneficial to the project for this simple change.

**Comment by marcosnils** [comment]
In case someone is interested I've deployed this change here: https://coderadio.marcosnils.now.sh with it's corresponding fork here: https://github.com/marcosnils/coderadio-client

I'm happy to review and merge PR's there if it's taking too long to ship in this repo.

**Comment by ahmadabdolsaheb** [comment]
@marcosnils this pr addresses #31.

@marcosnils, thank you for researching this and I completely understand the confusion. 
We are in the process of integrating coderadio to the universal navigation.  freeCodeCamp/freeCodeCamp#38008

Although your current solution resolves #31, it will be replaced with react-hotkeys at some point to make coderadio compatible with the main repo and standardize how we handle all keyboard shortcuts across services.

I would appreciate it if you could check if using react-hotkeys resolves #31 and we could build on your solution from there.

**Comment by marcosnils** [comment]
> I would appreciate it if you could check if using react-hotkeys resolves #31 and we could build on your solution from there.

That would require me to include react-hotkeys and replace all current shortcuts and make sure that everything works for that module. Seems like an extra work that's outside this PR scope. My suggestion would be to merge this PR and then let whomever works on adding `react-hotkeys` figure the way to make it work there. In any case, it's not me decision to make at this point.

**Comment by ahmadabdolsaheb** [comment]
Thank you for your contribution, @marcosnils.

**Pull request merged**
