### PR TITLE
shorthands method

### PR DESCRIPTION
**Pull request by vikky-10**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by texas2010** [comment]
Hi, Does there has an open issue with this?  if there is. please add the issue number here. Thank!

**Comment by ahmadabdolsaheb** [comment]
Thanks @mrstark-A, the proposed changes would change the placement of the message.
Screen Shot 2021-03-28 at 8 33 01 PM

**Comment by ahmadabdolsaheb** [comment]
We are closing this pr due to inactivity. Please let us know if it has been closed by mistake.

**Comment by vikky-10** [comment]
ok sorry for inactive, due to some reason thanks for reviewing my PR @ahmadabdolsaheb I defiantly check it out code once. thanks again, sir!!

**Pull request closed without merging**
