### PR TITLE
feat: Add basic song history.

### PR DESCRIPTION
**Pull request by Greenheart**
Awesome work with the new radio! It's got much better performance than YouTube.

Thought this feature was missing so I added a simple version :)

One known issue is that the song history won't update immediately after a song completes, but regularly every 20 seconds. This cause a slight delay when songs are changing.

Perhaps song history updates could happen once some event inside the embedded coderadio player happens? I don't know what event to listen to, but that would be a significant improvement.

image

### CODE REVIEW

**Comment by raisedadead** [comment]
This is a nice idea, we are thinking of making the page into a static react application and integrate it into the existing gatsby client app.

@ahmadabdolsaheb is doing a few tweaks to the current UI. 

I think you should totally log this as a feature request instead and then we could/should implement this in the Gatsby app.

Here is the Open source view version of the embed that we can look at for inspiration and pick up the logic from:

https://github.com/AzuraCast/AzuraCast/blob/master/web/static/vue/radio_player.vue

**Comment by Greenheart** [comment]
@raisedadead Thanks, that would be even better!

Which repo do you mean with "the existing gatsby client"? I'm familiar with Gatsby and could look at adding this feature if the core app is ready.

**Comment by raisedadead** [comment]
The main repo is now a monorepo and eventually we will have a page `coderadio` in the same that will make the coderadio available at something like `https://www.freecodecamp.org/coderadio`

**Comment by Greenheart** [comment]
Ah, I see. Thanks!

Let me know if there are any small tasks I could help with.

**Comment by raisedadead** [comment]
Hey we just updated the UI quite a bit. We can think of different approach to this. I am going to close this and create a new github issue for the same.

**Pull request closed without merging**
