### PR TITLE
feat: Save user volume to local storage

### PR DESCRIPTION
**Pull request by genesis-algorithms**
Hi! I've tried adding this feature before but didn't complete the requirements for it to be merged... Hope this time I get things right.

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Hey there @genesis-algorithms~!

As a heads up, you are welcome to push additional commits to an existing PR, rather than having to open and close them repeatedly. 🙂

**Comment by genesis-algorithms** [comment]
`X_X` Yep... I too just noticed that I'm spamming the issues section, sorry. Is there a way to update my pull requests code/commit without needing to add additional commits or reopening the issues?

I was force pushing to my fork combined with `git commit --amend --no-edit`.

**Comment by nhcarrigan** [comment]
Good news is it looks like the checks have passed.

Once you've pushed a commit, you generally don't want to `--amend` it. Instead, do your `git add` and `git commit` and push a *new* commit to the branch. This will not require the force flag.

**Comment by ahmadabdolsaheb** [comment]
Thank you for developing this feature, @genesis-algorithms. It works as expected.

The only UI nitpick is that the volume level seem to be at 50% upon initial load and then it would be adjusted after the music is played.

It would be great if we could have the volume bar reflect the value stored at localstorage instead. 

Let us know if you would need help with implementing that change.

**Comment by genesis-algorithms** [comment]
Hi, I've fixed the UI not reflecting the value stored in local storage on initial load (finally... :D). Thanks for your help!

**Review by nhcarrigan — APPROVED** [review]
LGTM~! 🥳 Tested locally, seems to store the volume correctly.

Congratulations on your first pull request to this project! We look forward to future contributions!

Please note that our workflow requires at least one additional approval before this can be merged. 🙂

**Comment by genesis-algorithms** [comment]
> LGTM~! 🥳 Tested locally, seems to store the volume correctly.
> 
> Congratulations on your first pull request to this project! We look forward to future contributions!
> 
> Please note that our workflow requires at least one additional approval before this can be merged. 🙂

😍😍

**Comment by ahmadabdolsaheb** [comment]
@genesis-algorithms, congrats on your first contribution. 🎆 🍰 🥳

**Pull request merged**
