### PR TITLE
feat: add Cypress

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This adds the basic Cypress setup and a single test to make sure it's working.  The project can be found [here](https://dashboard.cypress.io/projects/kqzjwp/runs).

To test it out locally `npm start` the client and then `cypress open` to fire up the UI.

We might want to make use of actions and `start-server-and-test`, but this gives us something to play with.

### CODE REVIEW

**Review by Ismailtlem — COMMENTED** [review]
The home.js file should not be home.spec.js ?
Are the scripts written in package.json good ?

**Comment by ahmadabdolsaheb** [comment]
This is a good initial setup. We could use the conventions used in the learn app  to expand our scripts and cypress tests.
We are using a similar naming convention on the learn app.
https://github.com/freeCodeCamp/freeCodeCamp/tree/master/cypress

**Comment by ojeytonwilliams** [comment]
Thanks for merging this @ahmadabdolsaheb.  

@Ismailtlem reached out to me over email with some queries, but I want to mirror those here in case another contributor comes across this:

- The commands "npm run cypress open" and "npm run cypress:open" should do the same thing - the only reason for including "cypress:open" is to guide people to the command they probably want when getting started.  "cypress open" won't work unless you have Cypress installed globally.
- cypress-install.js is our way of making sure that Cypress is only installed when it's going to be used.  It's invoked via "precypress" if you run any "cypress" command.
- Using .spec.js is probably clearer than .js, so if you'd prefer to use that that's cool.

**Comment by Ismailtlem** [comment]
thanks @ojeytonwilliams

**Pull request merged**
